name: gp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchaudio
  - librosa
  - scikit-learn
  - pandas
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pip:
    - wget
    - timm==0.4.5